# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a8da6591811a5d65b897cd6b0f4ed68954f4bb6c19473f7dc0dc20c113244b49edc9a08444f3ee51a566c1b8b5f21e7d7cca82a7936263e42862b325728a4d

test:
  secret_key_base: a4bc6b1bbb0c1e61fa29f76e65c791265be35a0307aacfb7b94e61f7f166c010d0458346c7b86940c535b6ba06a3c221fb92e3a0df15cb8806697458222504cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
